### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by drybjed** [george-hawkins/avahi-aliases-notes#1]
Hello,

This is a nice, clean solution for Avahi aliases. I would like to include it in my project, but I'm not sure what license is in effect. Can you [choose a license](https://choosealicense.com/) for your project and include it in the repository? Thanks.

**Comment by george-hawkins** [comment]
I've added a [license section](https://github.com/george-hawkins/avahi-aliases-notes#licenses) now and will update it if I get a reply from the original author of the Python script.

**Comment by george-hawkins** [comment]
OK - the original author replied and says he considers the Python script public domain.
